name: Go-test

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [opened, synchronize, edited]
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Run only local tests
      run: go test -v ./...
